/* This file was generated by SableCC (http://www.sablecc.org/). */

package assignlang.node;

import assignlang.analysis.*;

@SuppressWarnings("nls")
public final class AAssignStatement extends PStatement
{
    private TIdentifier _identifier_;
    private TOpequal _opequal_;
    private PAssignrest _assignrest_;

    public AAssignStatement()
    {
        // Constructor
    }

    public AAssignStatement(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") TOpequal _opequal_,
        @SuppressWarnings("hiding") PAssignrest _assignrest_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setOpequal(_opequal_);

        setAssignrest(_assignrest_);

    }

    @Override
    public Object clone()
    {
        return new AAssignStatement(
            cloneNode(this._identifier_),
            cloneNode(this._opequal_),
            cloneNode(this._assignrest_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignStatement(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public TOpequal getOpequal()
    {
        return this._opequal_;
    }

    public void setOpequal(TOpequal node)
    {
        if(this._opequal_ != null)
        {
            this._opequal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opequal_ = node;
    }

    public PAssignrest getAssignrest()
    {
        return this._assignrest_;
    }

    public void setAssignrest(PAssignrest node)
    {
        if(this._assignrest_ != null)
        {
            this._assignrest_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignrest_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._opequal_)
            + toString(this._assignrest_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._opequal_ == child)
        {
            this._opequal_ = null;
            return;
        }

        if(this._assignrest_ == child)
        {
            this._assignrest_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._opequal_ == oldChild)
        {
            setOpequal((TOpequal) newChild);
            return;
        }

        if(this._assignrest_ == oldChild)
        {
            setAssignrest((PAssignrest) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
